// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only

#include "classes.h"

/*!
    \class AlphaWidget
    \inmodule CatalogPagesTest
    \brief The first widget documented by the catalog fixture.

    AlphaWidget is a stand-in class whose only purpose is to show up
    in catalog pages generated by \\generatelist and \\annotatedlist.
*/

/*!
    \fn AlphaWidget::AlphaWidget()
    Constructs an AlphaWidget. No-op.
*/

/*!
    \class BetaWidget
    \inmodule CatalogPagesTest
    \brief The second widget documented by the catalog fixture.

    BetaWidget sits between AlphaWidget and GammaWidget in the sorted
    catalog output, so the fixture verifies that ascending and
    descending orders differ on a predictable three-entry list.
*/

/*!
    \fn BetaWidget::BetaWidget()
    Constructs a BetaWidget. No-op.
*/

/*!
    \class GammaWidget
    \inmodule CatalogPagesTest
    \brief The third widget documented by the catalog fixture.

    GammaWidget rounds out the three-entry catalog. With three
    entries the alphabetical ordering is unambiguous and the
    descending order likewise.
*/

/*!
    \fn GammaWidget::GammaWidget()
    Constructs a GammaWidget. No-op.
*/
